apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: juice-shop
  name: deployment-juice-shop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: juice-shop
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: juice-shop
    spec:
      containers:
      - image: bkimminich/juice-shop
        imagePullPolicy: Always
        name: juice-shop
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: juice-shop
  name: service-juice-shop
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: juice-shop
