apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test,audo-delete=no
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: web-nginx-module
              servicePort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: web-nginx-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nginx-module
  template:
    metadata:
      labels:
        app: web-nginx-module
    spec:
      containers:
        - name: web-nginx-module
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx-module
  namespace: default 
  labels:
    app: web-nginx-module
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: web-nginx-module